export const metaDataTableRows = [
    { label: "primary_accession", display_name: "Primary Accession", description: "Primary accession number." },
    { label: "country", display_name: "Country", description: "Country of origin." },
    { label: "host", display_name: "Host", description: "Host organism." },
    { label: "host_scientific_name", display_name: "Host Scientific Name", description: "Scientific name of the host." },
    { label: "EPA_major_clade", display_name: "EPA Major Clade", description: "Major clade from EPA analysis." },
    { label: "EPA_minor_clade", display_name: "EPA Minor Clade", description: "Minor clade from EPA analysis." },
    { label: "EPA_major_all", display_name: "All EPA Major Clades", description: "All major clade assignments." },
    { label: "EPA_minor_all", display_name: "All EPA Minor Clades", description: "All minor clade assignments." },
    { label: "collection_date", display_name: "Collection Date", description: "Collection date." },
    { label: "collection_day", display_name: "Collection Day", description: "Day of collection." },
    { label: "collection_mon", display_name: "Collection Month", description: "Month of collection." },
    { label: "collection_year", display_name: "Collection Year", description: "Year of collection." },
    { label: "update_date", display_name: "Last Updated Date", description: "Last date the record was updated." },
    { label: "create_date", display_name: "Creation Date", description: "Date the record was created." },
    {label: "pubmed_id", display_name: "PubMed ID", description: "Associated PubMed ID(s) for publications." },
    { label: "accession_type", display_name: "Accession Type", description: "Type of accession (reference or query)." },
    { label: "locus", display_name: "Locus", description: "The gene or sequence locus identifier." },
    { label: "length", display_name: "Sequence Length", description: "Length of the sequence in nucleotides." },
    { label: "data_source", display_name: "Data Source", description: "Source database of the sequence." },
    { label: "strandedness", display_name: "Strandedness", description: "Single or double stranded molecule." },
    { label: "molecule_type", display_name: "Molecule Type", description: "Type of molecule (DNA, RNA, etc.)." },
    { label: "topology", display_name: "Topology", description: "Linear or circular molecule." },
    { label: "division", display_name: "Division", description: "Biological division (e.g., Viruses, Bacteria)." },

    { label: "definition", display_name: "Definition", description: "Brief definition of the sequence." },
    
    { label: "accession_version", display_name: "Accession Version", description: "Version of the accession number." },
    { label: "gi_number", display_name: "GI Number", description: "GenInfo Identifier (GI) number." },
    { label: "source", display_name: "Source", description: "Source organism or laboratory." },
    { label: "organism", display_name: "Organism", description: "Name of the organism." },
    { label: "taxonomy", display_name: "Taxonomy", description: "Taxonomic classification." },
    
    { label: "exclusion_criteria", display_name: "Exclusion Criteria", description: "Criteria used to exclude the sequence." },
    { label: "exclusion_status", display_name: "Exclusion Status", description: "Indicates if the sequence is excluded." },
    
    { label: "mol_type", display_name: "Molecule Type (Short)", description: "Molecular type." },
    { label: "strain", display_name: "Strain", description: "Strain of the organism." },
    { label: "isolate", display_name: "Isolate", description: "Isolate name or identifier." },
    { label: "isolation_source", display_name: "Isolation Source", description: "Source from which the isolate was obtained." },
    { label: "db_xref", display_name: "Database Cross-Reference", description: "Database cross-references." },
    
    { label: "geo_loc", display_name: "Geographic Location", description: "Geographic location coordinates or description." },

    { label: "segment", display_name: "Segment", description: "Genomic segment." },
    { label: "serotype", display_name: "Serotype", description: "Serotype information." },
    { label: "genes", display_name: "Genes", description: "Genes present in the sequence." },
    { label: "cds_info", display_name: "CDS Info", description: "Coding sequence (CDS) information." },
    { label: "a", display_name: "A Count", description: "Number of adenine nucleotides." },
    { label: "t", display_name: "T Count", description: "Number of thymine nucleotides." },
    { label: "g", display_name: "G Count", description: "Number of guanine nucleotides." },
    { label: "c", display_name: "C Count", description: "Number of cytosine nucleotides." },
    { label: "n", display_name: "N Count", description: "Number of ambiguous nucleotides." },
    { label: "real_length", display_name: "True Sequence Length", description: "Real length of the sequence." },
    { label: "comment", display_name: "Comment", description: "Additional comments." },
    { label: "reference_number", display_name: "Reference Number", description: "Reference identifier number." },
    { label: "position", display_name: "Position", description: "Position information." },
    { label: "authors", display_name: "Authors", description: "Authors of the associated publication." },
    { label: "title", display_name: "Publication Title", description: "Title of the associated publication." },
    { label: "journal", display_name: "Journal", description: "Journal of publication." },
    
    { label: "major_LWR_score", display_name: "Major LWR Score", description: "Major clade likelihood weight ratio." },
    { label: "minor_LWR_score", display_name: "Minor LWR Score", description: "Minor clade likelihood weight ratio." },
    { label: "collection_date_validated", display_name: "Collection Date Validated", description: "Whether the collection date has been validated." },
    { label: "country_validated", display_name: "Country Validated", description: "Whether the country info has been validated." },
    { label: "host_validated", display_name: "Host Validated", description: "Whether the host info has been validated." },
    { label: "host_taxa_id", display_name: "Host Taxa ID", description: "Taxonomic ID of the host." },
    
];
